### ISSUE TITLE
Unable to open app on Android emulator

### ISSUE THREAD

**Issue by Chopin68** [cyrillkuettel/ncnn-android-yolov5#2]
App restart successful without requiring a re-install.
$ adb shell am start -n "com.tencent.ncnnyolox/com.tencent.ncnnyolox.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4620 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Late-enabling -Xcheck:jni
D/libnativebridge: call UnloadNativeBridge! state=1
D/yoloxncnn.cpp: JNI_OnLoad
E/NdkImageReader: AImageReader_getWindow
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/art: Before Android 4.1, method int androidx.appcompat.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/MainActivity: Ok: READ_EXTERNAL_STORAGE permission already granted
D/ncnn: loadModel 0xc7c500a0
D/ncnn: openCamera 0
W/NdkCamera: open
W/NdkCamera: open  0
E/ACameraManager: getCameraCharacteristics: Camera ID  does not exist!
E/ACameraManager: openCamera: cannot get camera characteristics for camera . err -10001
E/NdkCameraDevice: ACameraDevice_createCaptureRequest: invalid argument! device 0x0 request 0xb6f0fc50
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 4620 (ncent.ncnnyolox)

**Comment by cyrillkuettel** [comment]
I highly recommend using a real device (if you have one) for running ncnn models on the camera. This needs quite a lot of hardware resources, and the Emulator might not be able to handle it. 

If you really want to use the Emulator, you'll probably have to tell it which camera to use. See here: https://stackoverflow.com/questions/14012924/android-how-to-use-webcam-in-emulator

**Comment by Chopin68** [comment]
> 我强烈建议使用真实设备（如果你有的话）在相机上运行 ncnn 模型。这需要相当多的硬件资源，模拟器可能无法处理。
> 
> 如果您真的想使用模拟器，您可能必须告诉它使用哪个相机。见这里：[https ://stackoverflow.com/questions/14012924/android-how-to-use-webcam-in-emulator](https://stackoverflow.com/questions/14012924/android-how-to-use-webcam-in-emulator)

Thank you for your inspiration!I successfully made it call the USB camera through the UVC
